### ISSUE TITLE
fails to build from source (linux)

### ISSUE THREAD

**Issue by alexmyczko** [bgrabitmap/lazpaint#512]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1005672

is a new release planned? current one is 2 years old and doesnt build anymore.

debian will freeze in january 2023.

**Comment by circular17** [comment]
Hello,

I hope indeed to make a new release. When I can take some vacations to have enough spare time to fix most bugs. If I cannot add features, at least I would like to publish it so that a version is still available on Debian. I hope you will help me again to do that.

Regards

**Comment by rchastain** [comment]
Hello! I have just tried to compile a fresh copy of the repository, under Linux too.

The interesting part:

```
/home/roland/Documents/sources/lazpaint-rchastain/lazpaint/getfilesindir.inc(50,42) Error: (5000) Identifier not found "TMaskCaseSensitivity"
/home/roland/Documents/sources/lazpaint-rchastain/lazpaint/getfilesindir.inc(50,44) Error: (5000) Identifier not found "mcsPlatformDefault"
/home/roland/Documents/sources/lazpaint-rchastain/lazpaint/getfilesindir.inc(50,62) Error: (3203) Illegal expression
/home/roland/Documents/sources/lazpaint-rchastain/lazpaint/getfilesindir.inc(59,16) Error: (5000) Identifier not found "TMaskOptions"
/home/roland/Documents/sources/lazpaint-rchastain/lazpaint/getfilesindir.inc(59,28) Error: (5007) Error in type definition
/home/roland/Documents/sources/lazpaint-rchastain/lazpaint/getfilesindir.inc(80,40) Error: (5000) Identifier not found "mcsCaseInsensitive"
/home/roland/Documents/sources/lazpaint-rchastain/lazpaint/getfilesindir.inc(89,23) Error: (5000) Identifier not found "moDisableSets"
/home/roland/Documents/sources/lazpaint-rchastain/lazpaint/getfilesindir.inc(94,31) Error: (5000) Identifier not found "mcsCaseInsensitive"
/home/roland/Documents/sources/lazpaint-rchastain/lazpaint/getfilesindir.inc(95,25) Error: (5000) Identifier not found "moDisableSets"
/home/roland/Documents/sources/lazpaint-rchastain/lazpaint/getfilesindir.inc(95,40) Error: (5000) Identifier not found "moCaseSensitive"
```

**Comment by circular17** [comment]
I see. That's code I think I copied from somewhere in the LCL. I may need to rewrite it using more stable functions.

**Comment by rchastain** [comment]
Create a PR. Works for me but needs to be checked.

https://github.com/bgrabitmap/lazpaint/pull/513

**Comment by fredvs** [comment]
Hello.

@alexmyczko : do you have also plan for a LazPaint package for https://raspi.debian.net?

If yes, @circular17: I can test the script for Rpi ARM32 and AARCH64.

**Comment by rchastain** [comment]
I tried again to compile LazPaint, but using the "dev-lazpaint" branch.

I have a warning when I load the project.

![loadproject1](https://user-images.githubusercontent.com/13957204/182023493-62d47c91-747a-47a3-afbb-e6767d77e0ef.png)

After that, I have the errors that we have seen, in _getfilesindir.inc_. I replace that file with the one I retouched yesterday.

After that, I have this error:

```
utoolpolygon.pas(349,72) Error: identifier idents no member "ValidatedPointCount"
```

**Comment by circular17** [comment]
The error with TargetRasterImageList is because you need latest version of BGRAControls

**Comment by circular17** [comment]
If the location has changed, you need to reopen all packages : BGRAControls, LazPaintControls and BGRABitmap. This will update where they are read.

**Comment by circular17** [comment]
LazPaint compiled successfully with Lazarus 2.2.2. Do you get the errors with another version?

**Comment by onny** [comment]
I get following error trying to compile it on NixOS

```
(3104) Compiling ufilesystem.pas
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(930,1) Hint: (3123) "inherited" not yet supported inside inline procedure/funct>
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(930,1) Hint: (3124) Inlining disabled
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(945,1) Hint: (3123) "inherited" not yet supported inside inline procedure/funct>
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(945,1) Hint: (3124) Inlining disabled
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(1005,1) Hint: (3123) "inherited" not yet supported inside inline procedure/func>
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(1005,1) Hint: (3124) Inlining disabled
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(1010,1) Hint: (3123) "inherited" not yet supported inside inline procedure/func>
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(1010,1) Hint: (3124) Inlining disabled
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(963,1) Hint: (3123) "inherited" not yet supported inside inline procedure/funct>
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(963,1) Hint: (3124) Inlining disabled
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(968,1) Hint: (3123) "inherited" not yet supported inside inline procedure/funct>
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(968,1) Hint: (3124) Inlining disabled
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(950,1) Hint: (3123) "inherited" not yet supported inside inline procedure/funct>
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(950,1) Hint: (3124) Inlining disabled
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(955,1) Hint: (3123) "inherited" not yet supported inside inline procedure/funct>
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(955,1) Hint: (3124) Inlining disabled
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(997,1) Hint: (3123) "inherited" not yet supported inside inline procedure/funct>
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(997,1) Hint: (3124) Inlining disabled
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(1023,7) Note: (6058) Call to subroutine "function TFPGList<UFileSystem.TFileInf>
/nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.ppu:fgl.pp(1023,20) Note: (6058) Call to subroutine "function TFPGList<UFileSystem.TFileIn>
/build/source/lazpaint/ufilesystem.pas(1054,26) Error: (5038) identifier idents no member "GetFilesInDir"
/build/source/lazpaint/ufilesystem.pas(1086,28) Error: (5038) identifier idents no member "GetFilesInDir"
ufilesystem.pas(1217) Fatal: (10026) There were 2 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /nix/store/acwx7q0mnzxy0ri8bv2w3v887aijqkfy-fpc-3.2.2/bin/ppcx64 returned an error exitcode
Error: (lazarus) Compile Project, Mode: Release, Target: release/bin/lazpaint: stopped with exit code 1
Error: (lazbuild) failed compiling of project /build/source/lazpaint/lazpaint.lpi
```

**Comment by rchastain** [comment]
> LazPaint compiled successfully with Lazarus 2.2.2. Do you get the errors with another version?

Indeed, compilation successful with Laz 2.3.0. It fails with Laz 2.0.10 (even with BGRAControls updated).

**Comment by onny** [comment]
but Lazarus 2.3 is not yet released, right? If it's a unstable version I won't be able to package it

**Comment by circular17** [comment]
@onny GetFilesInDir is in the development version (dev-lazpaint). Maybe you tried with the master branch?

**Comment by circular17** [comment]
> > LazPaint compiled successfully with Lazarus 2.2.2. Do you get the errors with another version?
> 
> Indeed, compilation successful with Laz 2.3.0. It fails with Laz 2.0.10 (even with BGRAControls updated).

Oh ok, well this is an older version. I assume we are talking about building with latest stable version, which is 2.2.2

**Comment by rchastain** [comment]
Installed Lazarus 2.2.2. Compilation successful.

**Comment by onny** [comment]
> Installed Lazarus 2.2.2. Compilation successful.

How did you manage?

**Comment by rchastain** [comment]
> > Installed Lazarus 2.2.2. Compilation successful.
> 
> How did you manage?

I had to retouch the file _getfilesindir.inc_.

Here is the retouched file, in case you would to try.

[getfilesindir.inc.zip](https://github.com/bgrabitmap/lazpaint/files/9229278/getfilesindir.inc.zip)

**Comment by rchastain** [comment]
In fact **with Lazarus 2.2.2 I can compile LazPaint (master and dev-lazpaint) without any change!**

Sorry for the confusion.

**Comment by circular17** [comment]
I've merged new version 7.2 of LazPaint into master branch. Hopefully it will compile on all platforms.

I've put this version as prerelease for now. See details and schedule there:
https://forum.lazarus.freepascal.org/index.php/topic,12037.msg449509.html#msg449509

**Comment by alexmyczko** [comment]
somewhere appear to be hidden a version which is updated in debian:

```
# make
#lazbuild or fpc will determine what to recompile
lazbuild --build-mode=Release  lazpaintcontrols/lazpaintcontrols.lpk lazpaint/lazpaint.lpi
Error: (lazarus) invalid Lazarus directory "/usr/lib/lazarus/2.0.10/": directory not found
Error: (lazarus) Building failed: lazpaintcontrols/lazpaintcontrols.lpk
make: *** [Makefile:169: lazpaint] Error 2
```

i have /usr/lib/lazarus/2.2.0/ though

**Comment by circular17** [comment]
I wonder, maybe there is still some startup program/link to the old version on your system?

Or an old configuration in "~/.lazarus"? This directory can be deleted to reset.

**Comment by alexmyczko** [comment]
True, now it's only this:

```
# make
#lazbuild or fpc will determine what to recompile
lazbuild --build-mode=Release  lazpaintcontrols/lazpaintcontrols.lpk lazpaint/lazpaint.lpi
Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-iWTOTP"
Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-va" "compilertest.pas"
Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-iWTOTP" "-Px86_64" "-Tlinux"
Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-va" "compilertest.pas" "-Px86_64" "-Tlinux"
Error: (lazbuild) Broken dependency: lazpaintcontrols 0.2->bgracontrols (>=7.0)
```

**Comment by circular17** [comment]
Looks like dependent libraries are not recompiled. Maybe try "make clean" before.

**Comment by rchastain** [comment]
> ```
> lazbuild --build-mode=Release  lazpaintcontrols/lazpaintcontrols.lpk lazpaint/lazpaint.lpi
> ```
I didn't know that it was possible to install a package and build an application in one command. I always install packages first. Good to know !

**Comment by circular17** [comment]
Yes, that's actually pretty handy. In fact, I suppose I ensures the usage of the specified package. Otherwise if for some reason you would compile multiple project at the same time, using different version of the libraries, they could get mixed up.

**Comment by alexmyczko** [comment]
i'm not having luck, and i've got no idea what i'm doing wrong... what does it mean? 

`Error: (lazbuild) Broken dependency: lazpaintcontrols 0.2->bgracontrols (>=7.0)`

**Comment by circular17** [comment]
Here it says that lazpaintcontrols requires bgracontrols version 7.0 or higher.

Oh I got it, here this is just lazpaint repository, it does not contain bgracontrols nor bgrabitmap. You need to register both.

You need latest version of bgrabitmap and bgracontrols:
https://github.com/bgrabitmap/bgrabitmap
https://github.com/bgrabitmap/bgracontrols
Then from command line, go in each repo and type "make".

This is different from up-stream version for Debian, which bundles the three repos together (I have not made the up-stream yet).

**Comment by circular17** [comment]
Hello @alexmyczko 

I have updated the upstream repository: https://github.com/bgrabitmap/lazpaint-upstream

I've used the create_orig script to create an archive, signed it and sent it to mentors:
https://mentors.debian.net/package/lazpaint/

I suppose some warnings could be fixed. About the file "resources/lazpaint.res" it is binary so the line length does not matter.

**Comment by alexmyczko** [comment]
https://buildd.debian.org/status/package.php?p=lazpaint&suite=sid

**Comment by circular17** [comment]
Hmm there seem to be some errors that I did not encounter when compiling.
```
Error: (lazarus) unable to create package output directory "/usr/lib/lazarus/2.2.0/components/freetype/lib/x86_64-linux" of package "freetypelaz 1.0"
Error: (lazarus) unable to create package output directory "/usr/lib/lazarus/2.2.0/components/buildintf/units/x86_64-linux" of package "BuildIntf 1.0"
/usr/lib/lazarus/2.2.0/components/printers/./qt/qtprinters_h.inc(3,47) Fatal: (10022) Can't find unit qt5 used by OSPrinters
Error: (lazarus) Compile package Printer4Lazarus 0.5: stopped with exit code 1
```
I am not sure if the output directory is really a problem. But the error about not finding qt5 unit is surely causing the compilation to abort.

I am using the older distribution of Ubuntu (20.10) with older Lazarus (2.0.10). Maybe with a newer version I would get the error. I will try.

**Comment by circular17** [comment]
@alexmyczko I have been able to reproduce and then fix the compilation error by adding a rebuild all option (-B -r). That makes the build a bit slower, but at least there is no problem anymore with precompiled units.

As there are other minor fixes, I will make a new version LazPaint 7.2.2. I will tell you when the upstream is ready.

**Comment by fredvs** [comment]
Hello!

Congrats for the new release.
I arrive a few late, sorry.
What source must I use for the release of Rpi ARM32 and AARCH64?
Is it possible, like we did for previous release, to compile lazpaint via a script, without installing Lazarus (using only the Lazarus source)?

If yes, where is the script?

Thanks.

**Comment by circular17** [comment]
Hello Fred!

Well you are just in time in fact.

I suppose everything works like last time. All necessary files (except FPC and LCL) are in the upstream repository:
https://github.com/bgrabitmap/lazpaint-upstream

At the root, you have:
- ./custommakedeb: will produce a deb file with the LCL source and FPC location provided as parameter.
- ./configure: can configure the compilation to use a custom LCL source and FPC location. Call with --help for syntax. After that, you can produce the binaries and install them with "make"

**Comment by alexmyczko** [comment]
looks alot better, thanks a bunch!

**Comment by fredvs** [comment]
Hello Circular.

Ha, ok, I did try to compile lazpaint with lazpaint-main/lazpaint/lazpaint.prj  + ideU.
But compilation fails because lazpaint.res is not found.
So I try to create it with lazpaint/resources/createresource/createresource.pas.
But this one fails to compile too because createreource.res is not found !?

I will try with lazpaint-upstream. ( maybe lazpaint.res is added there ?)

**Comment by circular17** [comment]
Thank you Alex for helping me upload. There are indeed some green rows in the Debian build status.
https://buildd.debian.org/status/package.php?p=lazpaint&suite=sid
<img width="817" alt="Capture d’écran 2022-08-23 à 17 27 36" src="https://user-images.githubusercontent.com/9092455/186198890-5c9f05fd-084d-44d9-95df-4daea0088e31.png">

**Comment by fredvs** [comment]
Ha, here on lazpaint-main there no lazpaint.res
![ressouce](https://user-images.githubusercontent.com/3421249/186200425-ad26ff32-5a19-4948-9d28-b82415330918.png)

But I did not check yet /lazpaint-upstream.

**Comment by circular17** [comment]
Ah indeed, it is only in the upstream.

**Comment by circular17** [comment]
I've created an issue on FPC bugtracker for the compilation error on MIPSel architecture:
https://gitlab.com/freepascal.org/fpc/source/-/issues/39877

**Comment by fredvs** [comment]
Hello.
I finish test using lazpaint.prj  + laspaint.res (from upstream).

OK, compiles + runs perfectly with -O1 optimisation.
Maybe it works ok with > O1 (but in other fpc programs that I tested it was not stable with > O1).
![2022-08-23-184636_1366x768_scrot](https://user-images.githubusercontent.com/3421249/186218293-46dc0904-3787-4365-b675-64bff74d7f73.png)

I will attack compil + deb from lazpaint/upstream tonight.

**Comment by fredvs** [comment]
Hum, I get error while trying this: 

`sudo ./custommakedeb /home/pi/lazarus`

> make[2]: Leaving directory '/home/pi/lazpaint-upstream'
> make[1]: Leaving directory '/home/pi/lazpaint-upstream'
>    dh_autoreconf_clean -O--no-parallel
>    dh_clean -O--no-parallel
>  dpkg-source -b .
> dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../lazpaint_7.2.2.orig.tar.{bz2,gz,lzma,xz}
> dpkg-buildpackage: error: dpkg-source -b . subprocess returned exit status 25
> debuild: fatal error at line 1182:
> dpkg-buildpackage -us -uc -ui -d failed

?

And using ./configure:

> pi@raspberrypi:~/lazpaint-upstream $ ./configure --prefix=/home/pi/lazarus/
> For help type: ./configure --help
> Prefix set to: /home/pi/lazarus/
> ./configure: line 46: prefix: Permission denied
> Using lazbuild
> You can now type: make

And after make:

> pi@raspberrypi:~/lazpaint-upstream $ sudo make
> #lazbuild or fpc will determine what to recompile
> lazbuild -B -r --build-mode=Release  lazpaintcontrols/lazpaintcontrols.lpk lazpaint/lazpaint.lpi
> Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-iWTOTP"
> Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-va" "compilertest.pas"
> Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-iWTOTP" "-Parm" "-Tlinux"
> Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-va" "compilertest.pas" "-Parm" "-Tlinux"
> Error: (lazbuild) Broken dependency: lazpaintcontrols 0.2.1->bgracontrols (>=7.0)
> make: *** [Makefile:169: lazpaint] Error 3
> 

?

**Comment by circular17** [comment]
Oh ok, so "./custommakedeb" uses the "debuild", which means it needs to be used the same way an upstream is made. If you want to try that way, here is how to works. To do that, you need to put the repository inside a folder, for example "upstream". So it will be a subdirectory of that and must be called "lazpaint-7.2.2" (with a dash). From "upstream/lazpaint-7.2.2", call "./create_orig" to create the archive. Say "y" to first question to do that. But do not say "y" to the second question (when it asks to launch "debuild"). Basically, "./custommakedeb" is a way to continue the process, but instead with custom compile options.

The other route, is to start with "./configure", but you need to give it parameters you want. As I mentioned earlier, I invite you to call it with "--help" parameter to see the syntax. This way you will be able to specify Lazarus source directory. Also it won't use "lazbuild" so you won't have the package dependency issue.

**Comment by fredvs** [comment]
Hum, ok I will begin with ./configure ;-)

So _--help_ give this:

> pi@raspberrypi:~/lazpaint-upstream $ sudo ./configure --help
> For help type: ./configure --help
> Usage: ./configure [OPTIONS]
> 
>     --prefix=PREFIX
>         Specifies the install prefix.
>         By default prefix is "/usr/local"
>         For packages use "/usr"
> 
>     --lazdir=BASE_DIRECTORY_OF_LAZARUS
>         Specifies to compile with FPC using the specified Lazarus sources.
>         Otherwise lazbuild will be used.
> 
>     --fpcbin=FPC_BINARY
>         Specifies the command to call Free Pascal Compiler.
>         Default is "fpc"

But using ./configure + make give this (error dependency of bracontrol and use lazbuild):

```
pi@raspberrypi:~/lazpaint-upstream $ sudo ./configure --prefix=/home/pi/lazarus/ 
For help type: ./configure --help
Prefix set to: /home/pi/lazarus/
Using lazbuild
You can now type: make

pi@raspberrypi:~/lazpaint-upstream $ sudo make
#lazbuild or fpc will determine what to recompile
lazbuild -B -r --build-mode=Release  lazpaintcontrols/lazpaintcontrols.lpk lazpaint/lazpaint.lpi
Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-iWTOTP"
Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-va" "compilertest.pas"
Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-iWTOTP" "-Parm" "-Tlinux"
Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-va" "compilertest.pas" "-Parm" "-Tlinux"
Error: (lazbuild) Broken dependency: lazpaintcontrols 0.2.1->bgracontrols (>=7.0)
make: *** [Makefile:169: lazpaint] Error 3
```

**Comment by fredvs** [comment]
Ooops, it is **--lazdir**=/home/pi/lazarus/ 
OK, it compiles now, write you later.....

**Comment by fredvs** [comment]
Hello.

OK, compilation is ok and binary is in /release.

But running this binary gives strange color-wheel and layer tool:
![2022-08-23-221540_1366x768_scrot](https://user-images.githubusercontent.com/3421249/186258020-e566d8e3-7281-4de6-87de-6c8de7279cbd.png)

The one compiled with ideU seems ok:
![2022-08-23-221826_1366x768_scrot](https://user-images.githubusercontent.com/3421249/186258067-405921a5-2738-45ef-9fb4-0b3f72e4acd9.png)

May I know what fpc parameters is used in the **./configure** script?

**Comment by circular17** [comment]
Strange.

You can see the details near the end of the Makefile.

**Comment by fredvs** [comment]
OK, changed in makefile this:

Most important: Added parameter **-B** ( there is the same problem with MSEgui + BGRabitmap, when compiling a app the first time, without **-B** fpc ignore some {ifdef something}, once used **-B** it is ok and you may recompile without **-B**, the {ifdef xxx} will be nnot ignored)

Less important: Changed parameter **-O3** with _-O1_ ( O3 is not totally ready for ARM ).

Now binary in _/release_ runs ok:
![2022-08-23-231121_1366x768_scrot](https://user-images.githubusercontent.com/3421249/186266515-fa23668a-38a2-48a5-b4f9-5a68111fc4b3.png)

So, OK for _**lazpaint-no-install.**_
But for creating the deb, I feel lost, in _how_to_make_deb.txt_ it talks about this:
 _Depending on the target CPU, copy the folder 'lazpaint32' or 'lazpaint64'_

But I dont see that folders...

**Comment by circular17** [comment]
It is complicated to make it on your own. Rather use the tools provided.

**Comment by circular17** [comment]
I take a note of parameter -B. I had to use it to fix building with lazbuild.

**Comment by fredvs** [comment]
Huh, if you agree, I could give you a updated 

> It is complicated to make it on your own. Rather use the tools provided.

Are you talking about "./custommakedeb" ?
If so, I can try with your previous infos.

**Comment by fredvs** [comment]
Hello.

Here what I did:

Create _/home/pi/upstream/lazpaint-7.2.2_ directory.
Copy all files from _/home/pi/lazpaint-upstream/_ into _/home/upstream/lazpaint-7.2.2_

Then in console:
`cd /home/upstream/lazpaint-7.2.2`
`sudo ./create_orig`
`sudo ./custommakedeb /home/pi/lazarus/ `

OK, during the script lazpaint compiles ok and it is created some _lazpaint_7.2.2-1.debian.tar_ in /home/upstream 
![2022-08-24-020503_1366x768_scrot](https://user-images.githubusercontent.com/3421249/186287696-ba3db201-ba72-4999-b091-3177ab23138c.png)

After this the script continues with other compilation of Lazarus packages and finally stop with this message:
![2022-08-24-020606_1366x768_scrot](https://user-images.githubusercontent.com/3421249/186287881-e49f1406-b64e-4683-957a-a7c9c9cd1ddd.png)

I did try many times, also with **-B** in Makefile but always script ended with same error.

**Comment by circular17** [comment]
Thank you very much!

**Comment by fredvs** [comment]
> Thank you very much!

With pleasure!

> I've added -B -O1 to the Makefile when using FPC directly to maximize chances on experimental systems.

Good idea ( the binary-release for ARM-RPi have been compiled with **-B** and **-O1** in the Makefile)

About release for ARM-AARCH64 it will be for later because I dont have any laptop to re-create OS RPI-image (that is highly usefull because Linux for ARM-AARCH64 is far from stable and sure that compiling Lazpaint has few chance to work out-of-the-box.)

Fre;D

**Comment by circular17** [comment]
Ok. It can surely wait. Regards
